# Generated by Django 4.2.6 on 2023-10-20 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KL_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('nom_accessoire', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=5)),
                ('img', models.ImageField(upload_to='media')),
                ('description', models.CharField(max_length=250)),
                ('prix', models.IntegerField(default=0)),
                ('disponible', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('nom_collection', models.CharField(max_length=100)),
                ('Description', models.CharField(blank=True, max_length=250)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Modele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('nom_modele', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=5)),
                ('taille', models.CharField(max_length=5)),
                ('modele', models.ImageField(upload_to='media')),
                ('modele1', models.ImageField(upload_to='media')),
                ('modele2', models.ImageField(upload_to='media')),
                ('description', models.CharField(max_length=250)),
                ('prix', models.IntegerField(default=0)),
                ('disponible', models.BooleanField(default=False)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modeles', to='KL_app.collection')),
            ],
        ),
        migrations.CreateModel(
            name='Commandemodele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_cmd', models.DateTimeField(auto_now=True)),
                ('taille', models.CharField(max_length=5)),
                ('reception', models.CharField(max_length=30)),
                ('confirme', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('modele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KL_app.modele')),
            ],
        ),
        migrations.CreateModel(
            name='Commandeaccessoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_cmd', models.DateTimeField(auto_now=True)),
                ('reception', models.CharField(max_length=30)),
                ('confirme', models.BooleanField(default=False)),
                ('accessoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KL_app.accessoire')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='accessoire',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessoires', to='KL_app.collection'),
        ),
    ]
