# Generated by Django 4.2.6 on 2023-10-20 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KL_app', '0002_accessoire_collection_modele_commandemodele_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modele',
            name='modele1',
        ),
        migrations.RemoveField(
            model_name='modele',
            name='modele2',
        ),
    ]
