# Generated by Django 4.2.6 on 2023-10-20 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KL_app', '0003_remove_modele_modele1_remove_modele_modele2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessoire',
            old_name='img',
            new_name='img_accessoire',
        ),
        migrations.RenameField(
            model_name='modele',
            old_name='modele',
            new_name='img_modele',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='modele',
            name='taille',
        ),
    ]
