# Generated by Django 4.2.6 on 2023-10-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KL_app', '0004_rename_img_accessoire_img_accessoire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
